package model.support.allEnums;

public enum Skill {
    // Base skills
    MAIN_BATTLE_EXPERIENCE("MAIN_BATTLE_EXPERIENCE"),
    ARMOR_SKILL("ARMOR"),
    HAND_TO_HAND_FIGHT_SKILL("HAND_TO_HAND_FIGHT"),
    ONE_HANDED_WEAPON_SKILL("ONE_HANDED_WEAPON"),
    TWO_HANDED_WEAPON_SKILL("TWO_HANDED_WEAPON"),
    SHIELD_BLOCK_SKILL("SHIELD_BLOCK"),

    // Hand to hand skills
    HANDS_FIGHT_SKILL("HANDS_FIGHT"),
    FOOTS_FIGHT_SKILL("FOOTS_FIGHT"),
    RIGHT_HAND_FIGHT_SKILL("RIGHT_HAND_FIGHT"),
    LEFT_HAND_FIGHT_SKILL("LEFT_HAND_FIGHT"),
    RIGHT_FOOT_FIGHT_SKILL("RIGHT_FOOT_FIGHT"),
    LEFT_FOOT_FIGHT_SKILL("LEFT_FOOT_FIGHT"),

    // One-handed weapon skills
    KNIFE_SKILL("KNIFE"),
    SWORD_SKILL("SWORD"),
    AXE_SKILL("AXE"),
    MACE_SKILL("MACE"),
    HAMMER_SKILL("HAMMER"),

    // Two-handed weapon type
    TWO_HANDED_SWORD_SKILL("TWO_HANDED_SWORD"),
    TWO_HANDED_AXE_SKILL("TWO_HANDED_AXE"),
    TWO_HANDED_MACE_SKILL("TWO_HANDED_MACE"),
    TWO_HANDED_HAMMER_SKILL("TWO_HANDED_HAMMER"),
    SPEAR_SKILL("SPEAR"),
    HALBERD_SKILL("HALBERD"),
    STAFF_SKILL("STAFF"),

    // Shield skills
    LIGHT_SHIELD_SKILL("LIGHT_SHIELD"),
    MIDDLE_SHIELD_SKILL("MIDDLE_SHIELD"),
    HEAVY_SHIELD_SKILL("HEAVY_SHIELD"),

    // Armor skills
    CLOTH_ARMOR_SKILL("CLOTH_ARMOR"),
    LEATHER_ARMOR_SKILL("LEATHER_ARMOR"),
    CHAIN_ARMOR_SKILL("CHAIN_ARMOR"),
    SCALY_ARMOR_SKILL("SCALY_ARMOR"),
    LAT_ARMOR_SKILL("LAT_ARMOR");

    public String type;

    Skill(String type) {
        this.type = type;
    }
}
